version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=developer
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
