package utils

const (
	GITHUB_CLIENT_ID      = "GITHUB_CLIENT_ID"
	GITHUB_CLIENT_SECRET  = "GITHUB_CLIENT_SECRET"
	OPEN_AI_API_KEY       = "OPEN_AI_API_KEY"
	PAGE_SIZE             = 10
	BAD_REQUEST           = "BAD REQUEST EXCEPTION"
	INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR"
	NOT_FOUND_ERROR       = "NOT FOUND ERROR"
	FORBIDDEN_ERROR       = "FORBIDDEN ERROR"
	DATABASE_URL          = "DATABASE_URL"
	PORT                  = "PORT"
)
